### ISSUE TITLE
Packages missing making the repo obsolete ! 

### ISSUE THREAD

**Issue by nekojin116** [Nanousis/CarControllerTutorial#1]
The packages file is missing and is making this repo obsolete, all shaders fail to compile and scripts aren't working, please if you could re-upload it correctly it would solve the problem ! 
Thank you for you effort !

**Comment by Nanousis** [comment]
The package requires URP pipeline in order to work. Otherwise it is going to have compiler errors. Try installing the package to a URP project.

**Comment by nekojin116** [comment]
i fixed all errors, is the pull requests available ?

**Comment by nekojin116** [comment]
Send a pull request where i fixed all bugs, have a nice day !
